---
- name: Configure Vector DB EC2 instance to sync directories with S3 on startup and shutdown
  hosts: vector_db
  become: yes
  vars:
    s3_bucket_name: "dkedu"
    s3_folder_name: "rag1"  # Prefix in the S3 bucket where the files are located
    local_db_files_location: "/volumes/milvus"
  tasks:

    - name: Ensure the local directory exists
      file:
        path: "{{ local_db_files_location }}"
        state: directory
        mode: '0755'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install awscli
      apt:
        name: awscli
        state: present

    - name: Create the download-on-startup systemd service file from template
      template:
        src: download-on-startup.service.j2
        dest: /etc/systemd/system/download-on-startup.service
        mode: '0644'

    - name: Create the upload-on-shutdown systemd service file from template
      template:
        src: upload-on-shutdown.service.j2
        dest: /etc/systemd/system/upload-on-shutdown.service
        mode: '0644'
      
    - name: Reload systemd to pick up the new services
      command: systemctl daemon-reload

    - name: Enable the download-on-startup service
      systemd:
        name: download-on-startup.service
        enabled: yes
        state: started

    - name: Enable the upload-on-shutdown service
      systemd:
        name: upload-on-shutdown.service
        enabled: yes
        state: started
