---
- name: For all instances
  hosts: all
  become: true

  tasks:
    - name: Initial update yum cache
      yum:
        update_cache: true

    - name: Add initial dependencies
      yum:
        name: 
          - awscli
          - tree
        state: present

  roles:
    - role: dmytrokrynytsyn.components.fluentbit
      vars:
        fluentd_host: "{{ hostvars[inventory_hostname]['fluentd_ip'] }}"
    - role: dmytrokrynytsyn.components.node_exporter

- name: Docker
  hosts: frontend, backend, vectordb
  become: true
  roles:
    - role: dmytrokrynytsyn.components.docker

- name: Kafka cluster
  hosts: kafka
  become: true
  roles:
    - role: dmytrokrynytsyn.components.kafka_broker

<<<<<<< HEAD
- name: Redis primary
=======
- name: Redis 6 primary
>>>>>>> 4b9c2db54018b6b121515609d0a6407328e23c3c
  hosts: redis_primary
  become: true
  roles:
    - role: dmytrokrynytsyn.components.redis6_primary

<<<<<<< HEAD
- name: Redis secondary
=======
- name: Redis 6 replica
>>>>>>> 4b9c2db54018b6b121515609d0a6407328e23c3c
  hosts: redis_secondary
  become: true
  roles:
    - role: dmytrokrynytsyn.components.redis6_replica
      vars:
        redis_primary_host: "{{ hostvars[inventory_hostname]['redis_primary_host']}}"

- name: Elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - role: dmytrokrynytsyn.components.elasticsearch

- name: Fluentd
  hosts: fluentd
  become: true
  roles:
    - role: dmytrokrynytsyn.components.fluentd
      vars:
        elasticsearch_host: "{{ hostvars[inventory_hostname]['elasticsearch_ip'] }}"

- name: Kibana
  hosts: kibana
  become: true
  roles:
    - role: dmytrokrynytsyn.components.kibana
      vars:
        elasticsearch_host: "{{ hostvars[inventory_hostname]['elasticsearch_ip'] }}"

- name: Prometheus
  hosts: prometheus
  become: true
  roles:
    - role: dmytrokrynytsyn.components.prometheus
      vars:
        nodes_to_srcape: "{{ hostvars[inventory_hostname]['nodes_to_scrape']}}"

- name: Grafana
  hosts: grafana
  become: true
  roles:
    - role: dmytrokrynytsyn.components.grafana
      vars:
        prometheus_ip: "{{ hostvars[inventory_hostname]['prometheus_ip'] }}"

- name: Configure Vector DB
  hosts: vectordb
  become: true
  roles:
    - role: dmytrokrynytsyn.components.milvusdb

- name: Configure RAG backend service
  hosts: backend
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: dkrinitsyn/rag1backend:latest
        tag: latest
        source: pull
        force_source: true

    - name: Run Docker container
      community.docker.docker_container:
        name: rag1backend_container
        image: dkrinitsyn/rag1backend:latest
        state: started
        ports:
          - "80:80"
        env:
          VECTORDB_IP: "{{ hostvars[inventory_hostname]['vectordb_ip'] }}"
          OPEN_API_KEY: "{{ hostvars[inventory_hostname]['open_api_key'] }}"
          REDIS_IP: "{{ hostvars[inventory_hostname]['redis_primary_host'] }}"
          KAFKA_CONNECTION_STRING: "{{ hostvars[inventory_hostname]['kafka_connection_string'] }}"

- name: Configure RAG frontend service
  hosts: frontend
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: dkrinitsyn/rag1frontend
        tag: latest
        source: pull
        force_source: true

    - name: Run Docker container
      community.docker.docker_container:
        name: rag1frontend_container
        image: dkrinitsyn/rag1frontend:latest
        state: started
        env:
          SLACK_BOT_TOKEN: "{{ hostvars[inventory_hostname]['slack_bot_token'] }}"
          SLACK_APP_TOKEN: "{{ hostvars[inventory_hostname]['slack_app_token'] }}"
          DEFAULT_CHANNEL: "{{ hostvars[inventory_hostname]['default_channel'] }}"
          RAG_BACKEND_IP: "{{ hostvars[inventory_hostname]['backend_ip'] }}"
          KAFKA_CONNECTION_STRING: "{{ hostvars[inventory_hostname]['kafka_connection_string'] }}"
