---
- name: Docker for all
  hosts: all
  become: true

  tasks:
    - name: Initial update yum cache
      yum:
        update_cache: true

    - name: Add initial dependencies
      yum:
        name: 
          - awscli
          - tree
        state: present
    
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

- name: Configure Vector DB EC2 instance to sync directories with S3 on startup and shutdown
  hosts: vectordb
  become: true
  roles:
    - role: dmytrokrynytsyn.components.milvusdb

- name: Configure RAG backend service
  hosts: rag_backend
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: dkrinitsyn/rag1backend:latest
        tag: latest
        source: pull
        force_source: true

    - name: Run Docker container
      community.docker.docker_container:
        name: rag1backend_container
        image: dkrinitsyn/rag1backend:latest
        state: started
        ports:
          - "80:80"
        env:
          VECTORDB_IP: "{{ hostvars[inventory_hostname]['vectordb_ip'] }}"
          OPEN_API_KEY: "{{ hostvars[inventory_hostname]['open_api_key'] }}"

- name: Configure RAG frontend service
  hosts: rag_frontend
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: dkrinitsyn/rag1frontend
        tag: latest
        source: pull
        force_source: true

    - name: Run Docker container
      community.docker.docker_container:
        name: rag1frontend_container
        image: dkrinitsyn/rag1frontend:latest
        state: started
        env:
          SLACK_BOT_TOKEN: "{{ hostvars[inventory_hostname]['slack_bot_token'] }}"
          SLACK_APP_TOKEN: "{{ hostvars[inventory_hostname]['slack_app_token'] }}"
          DEFAULT_CHANNEL: "{{ hostvars[inventory_hostname]['default_channel'] }}"
          RAG_BACKEND_IP: "{{ hostvars[inventory_hostname]['rag_backend_ip'] }}"
