name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx to enable multi-platform builds if needed
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub or another registry (optional)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image for rag1backend
    - name: Build and push Docker image for rag1backend
      uses: docker/build-push-action@v4
      with:
        context: ./rag1backend
        file: ./rag1backend/Dockerfile
        push: true  # Set to false if you don't want to push the image
        tags: ${{ secrets.DOCKER_USERNAME }}/rag1backend:latest

    # Build and push Docker image for rag1frontend
    - name: Build and push Docker image for rag1frontend
      uses: docker/build-push-action@v4
      with:
        context: ./rag1frontend
        file: ./rag1frontend/Dockerfile
        push: true  # Set to false if you don't want to push the image
        tags: ${{ secrets.DOCKER_USERNAME }}/rag1frontend:latest
